
#  Benchmark
## Benchmarking CPC2, CNIT and CPAT lncRNAs prediction on rheMac10 reference 


#### Imports
```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rtracklayer);  library(stringr); library(ggplot2); library(grid); library(gridExtra); library(RColorBrewer); library(readr); library(matrixStats)
library(GenomicRanges); library(dplyr); library(zeallot); library(tximport); library(ggpubr); library(plyr); 
library(formattable)
library(DT)
library("htmltools")
library("webshot")    

export_formattable <- function(f, file, width = "100%", height = NULL, 
                               background = "white", delay = 0.2)
    {
      w <- as.htmlwidget(f, width = width, height = height)
      path <- html_print(w, background = background, viewer = NULL)
      url <- paste0("file:///", gsub("\\\\", "/", normalizePath(path)))
      webshot(url,
              file = file,
              selector = ".formattable_widget",
              delay = delay)
    }

# Import Utils
source(file.path("../utils/01_lncrna_annotation_utils.R"))
```

#### Read all the prediciton and reference files

```{r readPredictions, echo=FALSE}

# rheMac10 reference (download)
# ftp://ftp.ensembl.org/pub/release-100/gtf/macaca_mulatta/
ref <- import(file.path("/home/luisas/Desktop/cluster/gene_annotations/ensembl_release100/rheMac10/Macaca_mulatta.Mmul_10.100.gtf"))

# Table correspondence between transcripts and gene IDs 
df_ref <- distinct(data.frame(ref[!is.na(ref$transcript_id),]$transcript_id, ref[!is.na(ref$transcript_id),]$gene_id, stringsAsFactors = F))
names(df_ref) <- c("transcript_id", "gene_id")
rownames(df_ref) <- df_ref$transcript_id

ref_lnc <- ref[ref$gene_biotype %in% c("lncRNA", "antisense"),]
ref_lnc <- ref_lnc[ref_lnc$type == "gene", ]
ref_pc <- ref[ref$type == "gene" & ref$gene_biotype == "protein_coding",]

# ----------------------
#   CPC2 predictions
# ----------------------
cpc2 <- read.table(file.path("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/99_benchmark_annotation/01_predictions/CPC2/cpc2_pred.txt"))
names(cpc2) <- c("ID","transcript_length ","peptide_length","Fickett_score" , " pI", "ORF_integrity", "coding_probability","label")
# Extract transcript ids 
cpc2$transcript_id <- unlist(lapply(as.character(cpc2$ID), function(x) strsplit(x,"[(]")[[1]][1]))

# -----------------------------------------------
# Remove uncorcondant pred
cpc2$gene_id <-df_ref[cpc2$transcript_id,]$gene_id
unconcordant_prediction <- cpc2 %>%  dplyr::group_by(gene_id) %>% dplyr::summarise(Unique_Elements =  dplyr::n_distinct(label)) %>%  dplyr::filter( Unique_Elements > 1)
cpc2_concordant <- cpc2[!(cpc2$gene_id %in% unconcordant_prediction$gene_id),]
length(unique(cpc2_concordant$gene_id))
# -----------------------------------------------


# ----------------------
#   CPAT predictions
# ----------------------
cpat <- read.table(file.path("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/99_benchmark_annotation/01_predictions/CPAT/cpat_pred.ORF_prob.tsv"), header = T)
# Threshold reported by https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3616698/
# "score threshold of 0.364 gave the highest sensitivity and specificity (0.966 for both) for human data"
cutoff <-  0.364
cpat$label <- ifelse(cpat$Coding_prob > cutoff, "coding", "noncoding")
cpat$transcript_id <- unlist(lapply(as.character(cpat$ID), function(x) strsplit(x,"[(]")[[1]][1]))

# -----------------------------------------------
# Remove uncorcondant pred
cpat$gene_id <-df_ref[cpat$transcript_id,]$gene_id
unconcordant_prediction <- cpat %>%  dplyr::group_by(gene_id) %>% dplyr::summarise(Unique_Elements =  dplyr::n_distinct(label)) %>%  dplyr::filter( Unique_Elements > 1)
cpat_concordant <- cpat[!(cpat$gene_id %in% unconcordant_prediction$gene_id),]
length(unique(cpat_concordant$gene_id))
# -----------------------------------------------


# ----------------------
#   CNIT predictions
# ----------------------
cnit <- read.table(file.path("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/99_benchmark_annotation/01_predictions/CNIT/cnit_pred/CNCI2.index"), header = T, sep="\t", stringsAsFactors = F)
cnit$label <- cnit$index
cnit$transcript_id <- unlist(lapply(as.character(cnit$Transcript.ID), function(x) strsplit(x,"[(]")[[1]][1]))

# -----------------------------------------------
# Remove uncorcondant pred
cnit$gene_id <-df_ref[cnit$transcript_id,]$gene_id
unconcordant_prediction <- cnit %>%  dplyr::group_by(gene_id) %>% dplyr::summarise(Unique_Elements =  dplyr::n_distinct(label)) %>%  dplyr::filter( Unique_Elements > 1)
cnit_concordant <- cnit[!(cnit$gene_id %in% unconcordant_prediction$gene_id),]
length(unique(cnit_concordant$gene_id))
# -----------------------------------------------


# How many of the known lncRNAs (TRANSCRIPTS) are identified as such 
noncoding_cpc2_concordant_transcripts <- unlist(lapply(cpc2_concordant[cpc2_concordant$label == "noncoding",]$ID, function(x) strsplit(as.character(x),'(', fixed = T)[[1]][1]))
coding_cpc2_concordant_transcripts <- unlist(lapply(cpc2_concordant[cpc2_concordant$label == "coding",]$ID, function(x) strsplit(as.character(x),'(', fixed = T)[[1]][1]))

noncoding_cpat_concordant_transcripts <- unlist(lapply(cpat_concordant[cpat_concordant$label == "noncoding",]$ID, function(x) strsplit(as.character(x),'(', fixed = T)[[1]][1]))
coding_cpat_concordant_transcripts <- unlist(lapply(cpat_concordant[cpat_concordant$label == "coding",]$ID, function(x) strsplit(as.character(x),'(', fixed = T)[[1]][1]))


noncoding_cnit_concordant_transcripts <- unlist(lapply(cnit_concordant[cnit_concordant$index == "noncoding",]$Transcript.ID, function(x) strsplit(as.character(x),'(', fixed = T)[[1]][1]))
coding_cnit_concordant_transcripts <- unlist(lapply(cnit_concordant[cnit_concordant$index == "coding",]$Transcript.ID, function(x) strsplit(as.character(x),'(', fixed = T)[[1]][1]))


# How many of the known lncRNAs (GENES) are identified as such
noncoding_cpc2_concordant <- df_ref[(noncoding_cpc2_concordant_transcripts),]$gene_id
coding_cpc2_concordant <- df_ref[(coding_cpc2_concordant_transcripts),]$gene_id

noncoding_cpat_concordant <- df_ref[(noncoding_cpat_concordant_transcripts),]$gene_id
coding_cpat_concordant <- df_ref[(coding_cpat_concordant_transcripts),]$gene_id

noncoding_cnit_concordant <- df_ref[(noncoding_cnit_concordant_transcripts),]$gene_id
coding_cnit_concordant <- df_ref[(coding_cnit_concordant_transcripts),]$gene_id

```



```{r tableStats}
# ---------------------------------------------------------------------------------------------------------------
# Given a set of predicted lncRNAs and predicted PC genes, compares it with the references (ref_lnc, ref_pc)
# Calculates sensitivity, specificity and accuracy of a se
# Name: name of the tool, appears in the resulting dataframe
# ---------------------------------------------------------------------------------------------------------------

calc_stats_prediction <- function(noncoding_pred,coding_pred, name, ref_lnc.=ref_lnc, ref_pc.=ref_pc){
  # Predicted as lnc and and are lnc
  TP <- length(unique(noncoding_pred[noncoding_pred %in% ref_lnc.$gene_id ]))
  print(TP)
  # Predicted as pc but are lnc
  FN <- length(unique(coding_pred[coding_pred %in% ref_lnc.$gene_id ]))
  print(FN)
  # Predicted as pc and are pc
  TN <- length(unique(coding_pred[coding_pred %in% ref_pc.$gene_id ]))
  # Predicted as lnc but are pc
  FP <- length(unique(noncoding_pred[noncoding_pred %in% ref_pc.$gene_id ]))
  sensitivity <- (TP/(FN+TP))*100
  specificity <- (TN/(TN+FP))*100
  accuracy <- ((TP + TN)/(TP + TN + FP + FN))*100 
  df <- data.frame(name = name, sensitivity = sensitivity, specificity = specificity, accuracy = accuracy, stringsAsFactors = F)
  return(df)
}

# Intersection of the predictions
noncoding_intersection <- unique(intersect(noncoding_cpc2_concordant,intersect(noncoding_cnit_concordant, noncoding_cpat_concordant)))
coding_intersection <- unique(ref[!(ref$gene_id %in% noncoding_intersection), ]$gene_id)


# Union of the predictions
noncoding_union <- unique(union(noncoding_cpc2_concordant,union(noncoding_cnit_concordant, noncoding_cpat_concordant)))
coding_union <- unique(ref[!(ref$gene_id %in% noncoding_intersection), ]$gene_id)

cpc2_concordant_stats <- calc_stats_prediction(noncoding_cpc2_concordant, coding_cpc2_concordant, "cpc2_concordant")
cpat_concordant_stats <- calc_stats_prediction(noncoding_cpat_concordant, coding_cpat_concordant, "cpat_concordant")
cnit_concordant_stats <- calc_stats_prediction(noncoding_cnit_concordant, coding_cnit_concordant, "cnit_concordant")
intersection_stats <- calc_stats_prediction(noncoding_intersection, coding_intersection, "Intersection")
union_stats <- calc_stats_prediction(noncoding_union, coding_union, "Union")

stats_summary <- rbind(cpc2_concordant_stats, cpat_concordant_stats, cnit_concordant_stats, intersection_stats, union_stats)

# Visualize stats in a table
table <- formattable(stats_summary, 
            align = c("l",rep("r", NCOL(stats_summary) - 1)),
            list(`name` = formatter("span", style = ~ style(color = "grey", font.weight = "bold")), 
                 area(col = c(accuracy)) ~ normalize_bar("#ff9999", 0.2)))
#export_formattable(table,"Fig_S1A.png")

table

```



