---
title: "Untitled"
author: "Luisa Santus"
date: "2/28/2020"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rtracklayer)
library(dplyr)
library(ggplot2)
library(plyr)
library(ggpubr)

# Import Utils
source(file.path("../utils/01_lncrna_annotation_utils.R"))

ref_ensembl <- import("/home/luisas/Desktop/cluster/gene_annotations/ensembl_release100/rheMac10/Macaca_mulatta.Mmul_10.100.gtf") 

ref_ensembl_lnc  <- ref_ensembl[ref_ensembl$gene_biotype == "lncRNA",]
ref_ensembl_pc  <- ref_ensembl[ref_ensembl$gene_biotype == "protein_coding",]
ref_ensembl_notlnc <- ref_ensembl[ref_ensembl$gene_biotype != "lncRNA",]

export(ref_ensembl_lnc, "/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/rheMac10/ensembl_100_lnc.gtf")
export(ref_ensembl_pc, "/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/rheMac10/ensembl_100_pc.gtf")
export(ref_ensembl_notlnc, "/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/rheMac10/ensembl_100_notlnc.gtf")

# Human 

ref_ensembl <- import("/home/luisas/Desktop/cluster/gene_annotations/ensembl_release100/homo_sapiens/Homo_sapiens.GRCh38.100.gtf") 

table(ref_ensembl$transcript_biotype)
ref_ensembl_lnc  <- ref_ensembl[ref_ensembl$gene_biotype == "lncRNA",]
ref_ensembl_pc  <- ref_ensembl[ref_ensembl$gene_biotype == "protein_coding",]
ref_ensembl_notlnc <- ref_ensembl[ref_ensembl$gene_biotype != "lncRNA",]

export(ref_ensembl_lnc, "/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/Human//ensembl_100_lnc.gtf")
export(ref_ensembl_pc, "/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/Human//ensembl_100_pc.gtf")
export(ref_ensembl_notlnc, "/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/Human/ensembl_100_notlnc.gtf")




```

# Macaque 

```{r benchmark}

pcvslnc <- import("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/rheMac10/01_gffcompare/pcvslnc.annotated.gtf")
notlncvslnc <- import("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/rheMac10/01_gffcompare/notlncvslnc.annotated.gtf")

plot_stats_benchmark(pcvslnc)
plot_stats_benchmark(notlncvslnc)
```



# Human

```{r benchmark}

pcvslnc_human <- import("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/Human/01_gffocompare/pcvslnc.annotated.gtf")
notlncvslnc_human <- import("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/01_PreliminaryFiles_rheMac10/benchmark/Human//01_gffocompare/notlncvslnc.annotated.gtf")

plot_stats_benchmark(pcvslnc_human)
plot_stats_benchmark(notlncvslnc_human)


```

