---
title: "Untitled"
author: "Luisa Santus"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rtracklayer)
library(dplyr)
library(ggplot2)
library(plyr)
library(ggpubr)

col_lnc = "#870052"
col_mrna = "#2e88bf"
palette_plot_percentage <- c(col_lnc, col_mrna)

# Import Utils
source(file.path("../utils/01_lncrna_annotation_utils.R"))


theme_paper <- theme(legend.title = element_blank())+theme(panel.background = element_rect(fill = "white", colour = "white"))+theme(panel.background = element_rect(fill = "white", colour = "grey50"))+theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20), legend.text = element_text(size = 18))
```

## Check tissue effect 

```{r cpc2}


spleen <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/tissue_effect/00_spleen/")
wholeblood <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/tissue_effect/01_spleen_wholeblood/")
lymphnode <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/tissue_effect/02_spleen_wholeblood_lymphnode/")

library(purrr)
get_novel <- function(dir){
  name <- rev(unlist(lapply(str_split(dir, "/")[[1]],function(x) x[nchar(x) >= 1])))[1]
  assembly <- import(file.path(dir, "stringtie_merged_reference_guided.gtf"))
  assembly_stringtie <- assembly[assembly$source == "Stringtie",]
  gffcompare <- import(file.path(dir, "01_gffcompare/merged.annotated.gtf"))
  novel_u <- gffcompare[gffcompare$class_code %in% c("u"), ]
  novel_x <- gffcompare[gffcompare$class_code %in% c("x"), ]
  type <- c("intergenic","antisense", "all")
  n <- c(length(unique(novel_u$transcript_id)), length(unique(novel_x$transcript_id)), length(unique(novel_u$transcript_id))+length(unique(novel_x$transcript_id)))
  df <- data.frame(name = name ,n =n,  type = type )
  return(df)
}

tissue_effect <- do.call(rbind,(lapply(c(spleen,wholeblood, lymphnode), function(x) get_novel(x))))

tissue_effect$name <- c(rep("spleen: 21",3), rep("spleen+wb: 42",3), rep("spleen+wb+ln: 63",3))

library(viridis)
# Check tissue effect 

ggplot(data=tissue_effect, aes(x=name, y=n, group=type, color=type)) +
  geom_line() + geom_point()+
  scale_color_brewer(palette="Paired")+
  theme_paper+
  ylab("#Novel transcript")+xlab("")+
  theme(axis.text.x = element_text(angle=45, hjust = 1, size = 10))+  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) 

```



```{r effect }
wbni_10 <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/01_addsample/00_wbni_10/")
wbni_20 <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/01_addsample/01_wbni_20/")
wbni_30 <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/01_addsample/02_wbni_30/")

wbMIXinf_10 <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/02_add_sampleMIXinf/00_wbni_10/")
wbMIXinf_20 <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/02_add_sampleMIXinf/01_wbMIXinf_20/")
wbMIXinf_30 <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/02_add_sampleMIXinf/02_wbMINinf_30/")

wbsp <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/01_addsample/00_wbni_10/")
wbspleen <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/03_add_tissueNI/01_wbspleen/")
wbspleenln <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/03_add_tissueNI/02_wbspleenln/")


sample_effect <- do.call(rbind,(lapply(c(wbni_10,wbni_20, wbni_30, wbMIXinf_10, wbMIXinf_20, wbMIXinf_30,wbsp, wbspleen, wbspleenln ), function(x) get_novel(x))))

sample_effect_red <- sample_effect[sample_effect$type == "all", ]

sample_effect_red$stage <- unlist(lapply(sample_effect_red$name, function(x) str_split(x, "_")[[1]][1]))

sample_effect_red$stage <- (as.double(sample_effect_red$stage)+1)*10
sample_effect_red$test <- c(rep("sample",3), rep("sampleinfectionmix",3), rep("tissue",3))

ggplot(data=sample_effect_red, aes(x=stage, y=n, group=test, color=test)) +
  geom_line() + geom_point()+
  scale_color_brewer(palette="Paired")+
  theme_paper+
  ylab("#Novel transcript")+xlab("")+
  theme(axis.text.x = element_text(angle=45, hjust = 1, size = 10))+  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) 


```






```{r effect }
main <- ("/home/luisas/Desktop/cluster/data/99_Broad_benchmark/all")

all_sample_effect <- do.call(rbind,(lapply(c(list.dirs(main, recursive = F)), function(x) get_novel(x))))
all_sample_effect_red <-all_sample_effect
all_sample_effect_red$name <- as.double(as.character(all_sample_effect$name))
all_sample_effect_red$nsamples <- all_sample_effect_red$name * 10
ggplot(data=all_sample_effect_red, aes(x=nsamples, y=n, group=type, color=type)) +
  geom_line() + geom_point()+
  scale_color_brewer(palette="Paired")+
  theme_paper+
  ylab("#Novel transcript")+xlab("")+
  theme(axis.text.x = element_text(angle=45, hjust = 1, size = 10))+  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) 

```




