---
title: "Sc analysis"
author: "Luisa Santus"
date: "1/22/2020"
output: html_document
---


#  CREATE AND SAVE EXPRESION MATRICES TO COMPUTE THE NETWORK 

## 1. Imports
```{r Imports}
library(Seurat)
library(Matrix)

# In vivo 
immune.combined <- readRDS(file.path(data_path, "/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/03_prep/03_immune.combined.ready.rds"))
dim(immune.combined)

de_all<- readRDS(file.path(data_path,"/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/04_DE/de_all_stages.rds"))
```

# 2. Prepare the matrixes to calculate the networks on. One per celltype, only DE genes. 
```{r a}
monocyte <- immune.combined[,Idents(immune.combined)=="Monocyte"]
#b <- immune.combined[,Idents(immune.combined)=="B"]
#t <- immune.combined[,Idents(immune.combined)=="T"]

de_monocyte<- monocyte[rownames(monocyte) %in% unique(de_all[de_all$celltype == "Monocyte",]$primerid),]
#de_b <- b[rownames(b) %in% de_all,]
#de_t <- t[rownames(t) %in% de_all,]

# Monocytes DE
exprMatr_monocyte_de <- de_monocyte@assays$RNA@data
write.csv(t(exprMatr_monocyte_de), file.path(data_path,"/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/09_graph/matrix_monocytes_de.csv", row.names = FALSE))

```

