---
title: "Sc analysis"
author: "Luisa Santus"
date: "1/22/2020"
output: html_document
---


# Colocation/correlation analysis in vivo

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rtracklayer)
library(dplyr)
library(Seurat)
library(ggplot2)
library(RColorBrewer)
library(stringr)
library(edgebundleR)
library(igraph)
library(data.table)

#  Load utils 
source("../../utils/00_datapaths.R")
source("../../utils/06_colocation_utils.R")

cis_mono <- readRDS(file.path(data_path, "/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/07_colocation/cis_mono.rds"))
cis_B <-readRDS(file.path(data_path, "/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/07_colocation/cis_B.rds"))
cis_T  <- readRDS(file.path(data_path, "/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/07_colocation/cis_T.rds"))
cis_celltype <- readRDS(file.path(data_path, "/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/07_colocation/cis_celltype.rds"))

complete_cor <- readRDS(file.path(data_path, "/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/07_colocation/complete_cor.rds") )
final_summary <- readRDS(file.path(data_path, "00_Metadata/final_DE_summary.rds"))

#a <- cis_celltype
#a$pair <- paste(a$lnc, a$gene, sep = "-")
#length(unique(a$pair))

```




```{r chordGraph}

plot_colocation <- function(cis_celltype_plot, celltype){
  cis_celltype_plot <- cis_celltype_plot[,c("orth_lnc", "gene_name", "d")]
  colnames(cis_celltype_plot) <- c("rowname", "key", "value")
  cis_celltype_plot$key <- gsub("-unknown","", cis_celltype_plot$key)
  cis_celltype_plot$rowname <- gsub("-unknown","", cis_celltype_plot$rowname)
  cis_celltype_plot$rowname <- gsub(".", "-", cis_celltype_plot$rowname , fixed = T )

  v <- unique(c(cis_celltype_plot$key,cis_celltype_plot$rowname ))
  g <- graph.data.frame(cis_celltype_plot, directed=F, vertices=v)

  # Color
  V(g)$color  <- ifelse(!(V(g)$name %in% cis_celltype_plot$rowname), "grey", "#f72631")
  E(g)$color <- "grey"
  # Vertex size proportional to number of Edges
  #V(g)$size = degree(g)*20

  # Plot
  library(igraph)

  plot(g, layout = layout.circle, vertex.label=NA)
  eb <- edgebundle( g,  padding = 140, fontsize = 11, directed = F)
  
  saveEdgebundle(eb,file = paste(file.path(data_path,"/plots/04/colocation"), celltype,  ".html", sep = ""),  selfcontained = F)
}


plot_colocation(cis_mono, "Monocyte")


plot_colocation(cis_B, "B")

plot_colocation(cis_T, "T")



plot_colocation(cis_celltype, "All")


```


# How many cis pairs do we find?
```{r stats}
# Monocytes
stat_cis <- function(cis){
  # Number of pairs
  print(paste("Number of Pairs:", nrow(unique(cis[,c("lnc", "gene")]))))
  # Number of lnc
  print(paste("Number of Pairs:", length(unique(cis[,c("lnc")]))))
  print("----------")
}

stat_cis(cis_celltype)
stat_cis(cis_mono)
stat_cis(cis_B)
stat_cis(cis_T)

length(unique(cis_celltype$lnc))
```

```{r stats}
library(networkD3)
library(dplyr)

significant_plot <- complete_cor[complete_cor$pval < 0.05,]
significant_plot <- significant_plot[complete.cases(significant_plot),]

 
# A connection data frame is a list of flows with intensity for each flow
links <- significant_plot[significant_plot$celltype == "Monocyte",]

plot_s <- function(links){
  links$source <- links$lnc_orth
  links$target <- links$pc_name
  links$target <- gsub("-unknown", "", links$target)
  links$absrho <- abs(links$rho)
  links$absrho <- 1

  # From these flows we need to create a node data frame: it lists every entities involved in the flow
  nodes <- data.frame(
    name=c(as.character(links$source), 
    as.character(links$target)) %>% unique()
  )
   
  # With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
  links$IDsource <- match(links$source, nodes$name)-1 
  links$IDtarget <- match(links$target, nodes$name)-1
  
  links$group <- as.factor(ifelse(links$rho > 0, "type_a", "type_b"))
  
  ifelse(significant_plot$lnc_id %in% final_summary[!is.na(final_summary$community),]$gene_id, "GRAPH", "NOTGRAPH")
  nodes$group <- as.factor(c("my_unique_group"))

  my_color <- 'd3.scaleOrdinal() .domain(["type_a", "type_b", "my_unique_group"]) .range(["#69b3a2", "red", "grey"])'

  # Make the Network
  p <- sankeyNetwork(Links = links, Nodes = nodes,
                Source = "IDsource", Target = "IDtarget",
                Value = "absrho", NodeID = "name", 
                sinksRight=FALSE, colourScale = my_color,  LinkGroup="group", NodeGroup="group")
  p
  return(p)
}
plot_s( significant_plot[significant_plot$celltype == "Monocyte",])




print(plot_s( significant_plot[significant_plot$celltype == "T",]))




```


# Binomial TEST 
```{r stats}

# Load coloction information 
colocation_lnc <- readRDS(file.path(data_path, "02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/07_colocation/colocationLnc_df.rds"))
length(unique(colocation_lnc[,1]))
colocation_lnc <- data.frame(colocation_lnc)
colnames(colocation_lnc) <- c("lnc", "depc", "d")

# Only retain Expressed lncRNAs
robjectsdir_stats <- file.path(data_path,"02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/05_stats/")
all_lncrnas <- readRDS(file.path(robjectsdir_stats, "all_lncrnas.rds"))
colocation_lnc <-colocation_lnc[colocation_lnc$lnc %in% all_lncrnas,]
colocation_lnc <- colocation_lnc[!is.na(colocation_lnc$d),]

# Only retain colocated ones
colocation_lnc$d <- as.integer(as.character(colocation_lnc$d))
colocation_lnc$lnc <- (as.character(colocation_lnc$lnc))
colocation_lnc <- colocation_lnc[colocation_lnc$d < 1000000,]
length(unique(colocation_lnc$lnc))



de_all<- readRDS(file.path(data_path,"/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/04_DE/de_all_stages.rds"))


# A: DE lncRNAs in cis to DE pc
A <- (unique(cis_celltype$lnc))
# B: DE lncRNAs not in cis
B <- (setdiff(gsub("-unknown", "", unique(de_all[de_all$type == "lnc",]$primerid)), A))
# C: Ca Any (DE or not DE) lncRNA in cis to DE pc
C <- (setdiff(unique(colocation_lnc$lnc),A))
# D: not de and not in cis 
D <- setdiff(setdiff(setdiff(unique(all_lncrnas), A), B),C)


# 1. Are DE lncRNA mor in cs that non DE lncrnas ####
# cell-type specific
#                   cis              not-cis
# delncrna            x11               x12      
# not de lncrna               x21               x22
x11 <- length(A)
x21 <- length(C)
x12 <- length(B)
x22 <- length(D)
m_type <- matrix(c(x11, x12,x21,x22),2,2,byrow = TRUE)
rownames(m_type) <- c("DE","not DE")
colnames(m_type) <- c("cis","not cis")
m_type
fisher.test(m_type,alternative = "greater")

colocation_lnc[colocation_lnc$d < 1000000,]
colocation_lnc
```
