---
title: "Sc analysis"
author: "Luisa Santus"
date: "1/22/2020"
output: html_document
---


# Colocation/correlation analysis in vivo

```{r Imports}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Seurat)
library(ggpubr)
library(Matrix)
library(SingleCellExperiment)
library(stringr)
library(wesanderson)
library(rtracklayer)
library(ComplexHeatmap)
library(RColorBrewer)
library(ggplot2)
library(scales)
library(circlize)
library(reshape2)

theme_paper <- theme(legend.title = element_blank())+theme(panel.background = element_rect(fill = "white", colour = "white"))+theme(panel.background = element_rect(fill = "white", colour = "grey50"))+theme(axis.text = element_text(size = 18), axis.title = element_text(size = 20), legend.text = element_text(size = 18))

# Imports
source("../../utils/02_sc_utils.R")
source("../../utils/03_de_utils.R")
source("../../utils/04_utils_graph.R")

# LncRNAs
robjectsdir_stats <- file.path(data_path, "/02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/05_stats/")
all_lncrnas <- readRDS(file.path(robjectsdir_stats, "all_lncrnas.rds"))
length(unique(all_lncrnas))
annotated_mrnas <- readRDS(file.path(robjectsdir_stats,"annotated_mrnas.rds"))
```



# TEST 
```{r stats}

colocation_lnc <- readRDS(file.path(data_path, "02_scRNA-Seq_PBMCs/01_scRNA-Seq_inVivo_rhemac10/05_RObjects/07_colocation/colocationLnc_df.rds"))
length(unique(colocation_lnc[,1]))
colocation_lnc <- data.frame(colocation_lnc)
colnames(colocation_lnc) <- c("lnc", "depc", "d")
# Only retain expressed lnc
colocation_lnc <-colocation_lnc[colocation_lnc$lnc %in% all_lncrnas,]
# Only retain colocated ones
colocation_lnc <- colocation_lnc[colocation_lnc$d < 1000000,]
length(unique(colocation_lnc$lnc))

length(unique(cis_celltype$lnc))
binom.test(24,110, length(unique(colocation_lnc$lnc))/length(unique(all_lncrnas)), alternative="less")


table(colocation_lnc$lnc %in% all_lncrnas)
colocation_lnc

de_all_genes
```
