---
title: "DE_analysis"
author: "Luisa Santus"
date: "10/24/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exploratory analysis Zyagen vs Batch 

## Load Needed

Expression MDS from Zyagen and 
```{r  results='hide', message=FALSE, warning=FALSE}
library(ggplot2)
library(GenomicFeatures)
library(zeallot)
library(tidyverse)
library(tximport)
library(tximportData)
library(edgeR)
library(SummarizedExperiment)
library(DESeq2)
library("RColorBrewer")
library("dplyr")
library(plyr)
# Load Utils
projdir = "/home/luisas/Desktop/cluster/proj"
datadir <- "/home/luisas/Desktop/cluster/data/01_Ebola-RNASeq"

scripts_dir = file.path(projdir,"code/ebola/src/scripts/Analysis/utils")
source(file.path(scripts_dir,"de_utils.R"))
# Dirs
dir_hisat_zyagen = file.path(datadir, "02_RNA-Seq_old/03_hisat")
```

## Create Explorative MDS plots from HTSeq counts on CPMs

```{r echo=FALSE, results='hide'}
dir_hisat_all =  file.path(datadir, "02_RNA-Seq_old/03_hisat")
htseq_files <- iterate_files(dir_hisat_all, "UMI.f3.q60.umi_dedup.HTseq.gene_counts.tab")
dds <- create_dds(htseq_files,dir_hisat_all)
dge <- DGEList(counts = assays(dds)$counts, group = dds$condition, genes = rownames(dds), samples = colData(dds))
```


```{r echo=FALSE, results='hide'}
filter_and_plotMDS <- function(dds,dge,title){
  # Filter lowly expressed genes
  assays(dds)$logCPM <- cpm(dge, log = TRUE, prior.count = 0.01)
  mask <- rowMeans(assays(dds)$logCPM) > 1
  dds <- dds[mask, ]
  dge <- dge[mask, ]
  print(length(levels(dge$samples$group)))
  colors <- brewer.pal(n = length(levels(dge$samples$group)), name = 'Paired')
  col.cell <- colors[dge$samples$group]
  mds <- plotMDS(cpm(dge, log = TRUE,prior.count = 0.01), label= dge$samples$id , col=col.cell,main=" samples on genes CPM")
  
  par(xpd=T, mar=par()$mar+c(0,0,0,6))
  mds <- plotMDS(cpm(dge, log = TRUE,prior.count = 0.01), pch = 2, col=col.cell,main=" samples on genes CPM")
  legend(4.3,1.1, inset=c(-0.2,0), legend=levels(dge$samples$group), fill= unique(col.cell))
  par(mar=c(5, 4, 4, 2) + 0.1)
}
```


```{r echo=FALSE, results='hide'}

# Filters out lowly expressed genes, calc CPM, plot
filter_and_plotMDS_all <- function(dds,dge,title){
  # Filter lowly expressed genes
  assays(dds)$logCPM <- cpm(dge, log = TRUE, prior.count = 0.01)
  mask <- rowMeans(assays(dds)$logCPM) > 1
  dds <- dds[mask, ]
  dge <- dge[mask, ]
  dge$samples$tissue <-as.factor(dge$samples$tissue)
  colors <- brewer.pal(n = length(levels(dge$samples$tissue)), name = 'Paired')
  col.cell <- colors[dge$samples$tissue]
  mds <- plotMDS(cpm(dge, log = TRUE), label= dge$samples$group , col=col.cell,main=" samples on genes CPM")
  
  par(xpd=T, mar=par()$mar+c(0,0,0,6))
  mds <- plotMDS(cpm(dge, log = TRUE,prior.count = 0.01), pch = c(16,17)[dge$samples$group], col=col.cell,main=" samples on genes CPM")
  legend(5.5,2.6, inset=c(-0.2,0), legend=levels(dge$samples$group),  pch =c(16,17) )
  legend(5.5,0.9, inset=c(-0.2,0), legend=unique(dge$samples$tissue),  fill= unique(colors[dge$samples$tissue]))
  par(mar=c(5, 4, 4, 2) + 0.1)
}
32490+44209
filter_and_plotMDS_all(dds,dge)
```


```{r echo=FALSE, results='hide'}
mask <- dds$condition == "Zyagen"
dds_zyagen <- dds[,mask]
dge_zyagen <- DGEList(counts = assays(dds_zyagen)$counts, group = dds_zyagen$tissue, genes = rownames(dds_zyagen), samples = colData(dds_zyagen))

# Filters out lowly expressed genes, calc CPM, plot
filter_and_plotMDS(dds_zyagen,dge_zyagen)
```

```{r echo=FALSE, results='hide'}
mask <- dds$condition == "Batch01"
dds_batch <- dds[,mask]
dge_batch <- DGEList(counts = assays(dds_batch)$counts, group = dds_batch$tissue, genes = rownames(dds_batch), samples = colData(dds_batch))

# Filters out lowly expressed genes, calc CPM, plot
filter_and_plotMDS(dds_batch,dge_batch)
```
```{r echo=FALSE, results='hide'}
mask <- dds_batch$id != "RA0223"
dds_batch_nora <- dds_batch[,mask]
dge_batch_nora <- DGEList(counts = assays(dds_batch_nora)$counts, group = dds_batch_nora$tissue, genes = rownames(dds_batch_nora), samples = colData(dds_batch_nora))

# Filters out lowly expressed genes, calc CPM, plot
filter_and_plotMDS(dds_batch_nora,dge_batch_nora)
```

```{r echo=FALSE, results='hide'}
mask1 <- dds$condition == "Batch01" 
mask2 <- dds$tissue == "Liver"
mask <- mask1 & mask2 
dds_filtered <- dds[,mask]
dds_filtered$tissue
dge_batch_blood <- DGEList(counts = assays(dds_filtered)$counts, group = dds_filtered$dpo, genes = rownames(dds_filtered), samples = colData(dds_filtered))
# Filters out lowly expressed genes, calc CPM, plot
filter_and_plotMDS(dds_filtered,dge_batch_blood)


dds <- dds_filtered
dge <- dge_batch_blood

  assays(dds)$logCPM <- cpm(dge, log = TRUE, prior.count = 0.01)
  mask <- rowMeans(assays(dds)$logCPM) > 1
  dds <- dds[mask, ]
  dge <- dge[mask, ]
  print(length(levels(dge$samples$group)))
  colors <- brewer.pal(n = length(levels(dge$samples$group)), name = 'Paired')
  col.cell <- colors[dge$samples$group]
  mds <- plotMDS(cpm(dge, log = TRUE,prior.count = 0.01), label= dge$samples$group , col=col.cell,main=" samples on genes CPM")
  
  par(xpd=T, mar=par()$mar+c(0,0,0,6))
  mds <- plotMDS(cpm(dge, log = TRUE,prior.count = 0.01),label= dge$samples$id , col="blue",main="Liver")
  #legend(2.2,0.2, inset=c(-0.2,0), legend=levels(dge$samples$group), fill= unique(col.cell))
  par(mar=c(5, 4, 4, 2) + 0.1)

# Filters out lowly expressed genes, calc CPM, plot
filter_and_plotMDS(dds,dge)
```






# Explore library sizes
```{r echo=FALSE, results='hide'}
# Check distributions of samples using boxplots
par(mar=c(10,10,4,2)) # increase y-axis margin.
colors <- brewer.pal(n = length(levels(dge$samples$tissue)), name = 'Paired')
col.cell <- colors[dge$samples$tissue]

density.group <- c(20,90)[dge$samples$group]
colnames(dge) <-  paste(dge$samples$tissue,dge$samples$id,sep="_")
barplot(dge$samples$lib.size,names=colnames(dge),las=2,  col = col.cell, density=density.group)

# Add a title to the plot
title("Library Sizes")
```


```{r echo=FALSE, results='hide'}

boxplot_logcpms <- function(dge){
  logcounts <- cpm(dge,log=TRUE, prior.count = 0.01)
  # Check distributions of samples using boxplots
  colors <- brewer.pal(n = length(levels(dge$samples$group)), name = 'Paired')
  col.cell <- colors[dge$samples$group]
  
  colnames(logcounts) <- dge$samples$group
  boxplot(logcounts, xlab="", ylab="Log2 counts per million"
          ,las=2,
          col = col.cell,
          notch = TRUE
          )
  # Let's add a blue horizontal line that corresponds to the median logCPM
  abline(h=median(logcounts),col="blue")
  title("Boxplots of logCPMs")
}

```

```{r distRawExpAll, echo=FALSE, fig.height=4, fig.width=10, out.width="800px", fig.cap="Non-parametric density distribution of expression profiles per sample.", message=FALSE}
library(geneplotter)

assays(dds_zyagen)$logCPM <- cpm(dge_zyagen, log = TRUE,prior.count = 0.01)
mask <- rowMeans(assays(dds_zyagen)$logCPM) > 1
dds_zyagen_filter <- dds_zyagen[mask, ]
dge_zyagen_filter <- dge_zyagen[mask, ]

par(mfrow = c(1, 1), mar = c(4, 5, 1, 1))
multidensity(as.list(as.data.frame(assays(dds_zyagen)$logCPM)), xlab = "log2 CPM", legend = NULL,
             main = "Zyagen_all", cex.axis = 1.2, cex.lab = 1.5, las = 1)

par(mfrow = c(1, 1), mar = c(4, 5, 1, 1))
multidensity(as.list(as.data.frame(assays(dds_zyagen_filter)$logCPM)), xlab = "log2 CPM", legend = NULL,
             main = "Zyagen_filter", cex.axis = 1.2, cex.lab = 1.5, las = 1)


assays(dds_batch)$logCPM <- cpm(dge_batch, log = TRUE, prior.count = 0.01)
mask <- rowMeans(assays(dds_batch)$logCPM) > 1
dds_batch_filter <- dds_batch[mask, ]
dds_batch_filter <- dds_batch[mask, ]

par(mfrow = c(1, 1), mar = c(4, 5, 1, 1))
multidensity(as.list(as.data.frame(assays(dds_batch)$logCPM)), xlab = "log2 CPM", legend = NULL,
             main = "Batch_all", cex.axis = 1.2, cex.lab = 1.5, las = 1)

par(mfrow = c(1, 1), mar = c(4, 5, 1, 1))
multidensity(as.list(as.data.frame(assays(dds_batch_filter)$logCPM)), xlab = "log2 CPM", legend = NULL,
             main = "Batch_all", cex.axis = 1.2, cex.lab = 1.5, las = 1)

RA0223 <- dds_batch[,dds_batch$id == "RA0223"]
par(mfrow = c(1, 1), mar = c(4, 5, 1, 1))
multidensity(as.list(as.data.frame(assays(RA0223)$logCPM)), xlab = "log2 CPM", legend = NULL,
             main = "RA0223", cex.axis = 1.2, cex.lab = 1.5, las = 1)

RA0223 <- dds_batch_filter[,dds_batch_filter$id == "RA0223"]
par(mfrow = c(1, 1), mar = c(4, 5, 1, 1))
multidensity(as.list(as.data.frame(assays(RA0223)$logCPM)), xlab = "log2 CPM", legend = NULL,
             main = "RA0223-filter", cex.axis = 1.2, cex.lab = 1.5, las = 1)
```



