---
title: "02a_Umis"
author: "Luisa Santus"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Umis

I want to explore the duplicates removal through umis.

1. Look how many duplicates we are removing
2. Look at the correlation between samples of the same tissues ( We expect it to be higher)


## Number of Duplicates removed
```{r results='hide', message=FALSE, warning=FALSE}
library(zeallot)
library(ggplot2)
library(grid)
library(gridExtra)

projdir = "/home/luisas/Desktop/cluster/proj"
datadir <- "/home/luisas/Desktop/cluster/data/01_Ebola-RNASeq"

scripts_dir = file.path(projdir,"code/ebola/src/scripts/Analysis/utils")
source(file.path(scripts_dir,"mapping_qa.R"))
source(file.path(scripts_dir,"de_utils.R"))

extract_counts <- function(counts_files){
  counts <- list()
  for(file_counts in counts_files){
    # Extract tissue, sample and lane from filename of the hisat2 mapping reports
    c(tissue,sample, sample_name)  %<-% get_info_sample_counts(file_counts)
    # Error handling 
    if(! file.exists(file_counts)){print(paste0("File does not exits ",file_counts))}
    counts[[sample_name]] <- read.csv(file_counts,sep="\t",header =F) 
  }
  counts_df<-do.call(cbind.data.frame,
                     lapply(1:length(counts), function(i) counts[[i]][,2]))
  rownames(counts_df)<-counts[[1]][,1]
  colnames(counts_df)<-names(counts)
  return(counts_df)
}

extract_counts_method <- function(counts_zyagen_md, counts_zyagen_umi, counts_zyagen_filter){
  df_md_z <- data.frame("total" =  t(counts_zyagen_md[1,]),  type = "Remove Duplicates")
  df_md_z$sample <- rownames(df_md_z)
  df_umi_z <- data.frame("total" =  t(counts_zyagen_umi[1,]),  type = "Dedup Umis")
  df_umi_z$sample <- rownames(df_umi_z)
  df_filter_z <- data.frame("total" =  t(counts_zyagen_filter[1,]),  type = "After filtering")
  df_filter_z$sample <- rownames(df_filter_z)
  df_zyagen <-rbind(df_md_z, df_umi_z, df_filter_z)
  colnames(df_zyagen) <- c("total","type", "sample")
  return(df_zyagen)
}

barplot_counts_mdvsumi <- function(inpath_counts_zyagen,inpath_counts_batch, outpath){
  pattern_counts_filter = "q60.n_reads.txt"
  pattern_counts_md = "md.n_reads.txt"
  pattern_counts_umi = "umi_dedup.n_reads.txt"
  # Extract count files
  counts_zyagen_md <-extract_counts(iterate_files(inpath_counts_zyagen, pattern_counts_md))
  counts_zyagen_umi <-extract_counts( iterate_files(inpath_counts_zyagen, pattern_counts_umi))
  counts_zyagen_filter <-extract_counts( iterate_files(inpath_counts_zyagen, pattern_counts_filter))
  
  counts_batch_md <-extract_counts(iterate_files(inpath_counts_batch, pattern_counts_md))
  counts_batch_umi <-extract_counts(iterate_files(inpath_counts_batch, pattern_counts_umi))
  counts_batch_filter <-extract_counts( iterate_files(inpath_counts_batch, pattern_counts_filter))
  

  # Barplots 
  png(paste0(outpath,"zyagen_batch_md_umi.png"),width = 1900,height = 500)
  options(scipen=1000)
  par(mfrow=c(1,2))
  par(oma=c(8,2,0,0),xpd=NA)
  
  df_zyagen <- extract_counts_method(counts_zyagen_md, counts_zyagen_umi, counts_zyagen_filter)
  df_batch <- extract_counts_method(counts_batch_md, counts_batch_umi, counts_batch_filter)

  dodge <- position_dodge(width = 0.9)
  p <- ggplot(data=df_zyagen, aes(x= sample, y=total, fill=type,las=2)) +
    geom_bar(stat="identity", position=dodge, width=0.9)+ scale_fill_manual(values=c( "grey","#56B4E9","#E69F00"))+
    theme(axis.text.x = element_text(face = "bold", color = "black", 
                                       size = 15, angle = 45,  hjust = 1))+
    theme(axis.text.y = element_text(color = "black", 
                                     size = 10,  hjust = 1))+
    theme(legend.position = "none")+ xlab("")+ylab("")+ylim(0,68000000)
  
  p1 <- ggplot(data=df_batch, aes(x= sample, y=total, fill=type,las=2)) +
    geom_bar(stat="identity", position=dodge, width=0.9) + scale_fill_manual(values=c( "grey", "#56B4E9","#E69F00"))+
    theme(axis.text.x = element_text(face = "bold", color = "black", 
                                     size = 12, angle = 45,  hjust = 1))+
    theme(axis.text.y = element_text(color = "black", 
                                     size = 10,  hjust = 1))+
    theme(legend.title=element_blank())+ xlab("")+ylab("")+ylim(0,68000000)
  
  grid.arrange(p,p1,nrow=1)
  dev.off()
  p
  p1
  grid.arrange(p,p1,nrow=1)
}

```


```{r pressure, echo=FALSE}
hisat <- file.path(datadir, "02_RNA-Seq_old/03_hisat")
hisat_zyagen <- file.path(hisat, "Zyagen")
hisat_batch <- file.path(hisat, "Batch01")
outpath <- file.path(projdir,"data/plots/00a_umis/")
plots <-barplot_counts_mdvsumi(hisat_zyagen,hisat_batch, outpath)
```


## Correlation btw samples when using different duplicate removal methods

```{r pressure, echo=FALSE}
htseq_files_filter <- iterate_files(hisat_zyagen, "UMI.f3.q60.HTseq.gene_counts.tab")
htseq_files_md <- iterate_files(hisat_zyagen, "UMI.f3.q60.md.HTseq.gene_counts.tab")
htseq_files_umis <- iterate_files(hisat_zyagen, "UMI.f3.q60.umi_dedup.HTseq.gene_counts.tab")



dds_umis <-create_dds(htseq_files_umis, hisat)
dds_md <-create_dds(htseq_files_md, hisat)
dds_filter <-create_dds(htseq_files_filter, hisat)


# Correlation heatmaps
plot_counts_heatmap(dds_umis, paste(outpath,"heatmap_umi_dedup_pearson.png"), "pearson")
plot_counts_heatmap(dds_md, paste(outpath,"heatmap_md_pearson.png"), "pearson")
plot_counts_heatmap(dds_filter, paste(outpath,"heatmap_filter_pearson.png"), "pearson")

filter_dds<- function(dds_input, tissue){
  dds<- dds_input[,dds_input$tissue == tissue]
  dge <- DGEList(counts = assays(dds)$counts, group = dds$condition, genes = rownames(dds), samples = colData(dds))
  assays(dds)$logCPM <- cpm(dge, log = TRUE, prior.count = 0.01)
  mask <- rowMeans(assays(dds)$logCPM) > 6
  dds <- dds[mask, ]
  return(dds)
}
```



```{r pressure, echo=FALSE}

df_a <- data.frame()
for ( tissue in unique(dds_umis$tissue)){
  dds_tissue_1 <- dds_umis[,dds_umis$tissue == tissue]
  # Check if they have more than one sample
  if (length(dds_tissue_1$id) > 1){

    tissue <- tissue
 
    dds_u <- filter_dds(dds_umis, tissue)
    umis <- as.matrix(cor(assays(dds_u)$logCPM, method = "spearman"))
    df_umis <- data.frame("cor" =  as.numeric(umis[2]), "tissue" = tissue, "method" = "umi") 
    
    dds_m <- filter_dds(dds_md, tissue)
    md <- as.matrix(cor(assays(dds_m)$logCPM, method = "spearman"))
    df_md <- data.frame("cor" =  as.numeric(md[2]), "tissue" = tissue, "method" = "md") 
    
    dds_f <- filter_dds(dds_filter, tissue)
    filter <- as.matrix(cor(assays(dds_f)$logCPM, method = "spearman"))
    df_filter <- data.frame("cor" =  as.numeric(filter[2]), "tissue" = tissue, "method" = "filter")
    
    df_a<- rbind(df_a, df_md, df_filter, df_umis)
  }
}
  # Check if they have more than one sample
  
ggplot(df_a, aes(x=tissue, y=cor, fill=method))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_text(aes(label=cor), position=position_dodge(1), color="black", size=3.5,  hjust=1.5
)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()+ 
  coord_flip(ylim=c(0.1,1))

```


## About the expression Levels 

I need 4 bins for expression levels 

```{r pressure, echo=FALSE}
tissue <- "Adrenal"
sample <- "160421"

remove_genes_below <- function(dds, threshold){
  mask1 <- rowMeans(assays(dds)$logCPM) > threshold
  dds_1 <- dds[mask1, ]
  return(dds_1)
}

prepare_difference_dds <- function(dds_umis, dds_md, tissue, sample){
  dds_umis <- dds_umis[,dds_umis$tissue == tissue]
  dds_md <- dds_md[,dds_md$tissue == tissue]
  dds_umis <- dds_umis[,dds_umis$id == sample]
  dds_md <- dds_md[,dds_md$id == sample]
  assays(dds_umis)$difference <- assays(dds_umis)$count - assays(dds_md)$count
  dge <- DGEList(counts = assays(dds_umis)$counts, group = dds_umis$condition, genes = rownames(dds_umis), samples = colData(dds_umis))
  assays(dds_umis)$logCPM <- cpm(dge, log = TRUE, prior.count = 0.01)
  return(dds_umis)
}


calc_df_for_thresholds <- function(dds_umis_difference, thresholds){
  df <- data.frame()
  for(threshold in thresholds){
    dds_1 <- remove_genes_below(dds_umis_difference,threshold )
    difference1 <- as.vector(assays(dds_1)$difference)
    df <- rbind(df, data.frame(dif = difference1, threshold = threshold, tissue = tissue))
  }
  return(df)
}

dds_umis_difference <- prepare_difference_dds(dds_umis, dds_md, tissue, sample)

thresholds <- c(0.1,1,2,3,4)
df <- calc_df_for_thresholds(dds_umis_difference, thresholds)
boxplot(df$dif ~ df$threshold, names = thresholds,  outline = FALSE, col = "lightblue", main = tissue)

thresholds <- c(0.1,1,2,3,4,5,6,7,8)
df <- calc_df_for_thresholds(dds_umis_difference, thresholds)
boxplot(df$dif ~ df$threshold, names = thresholds,  outline = FALSE, col = "lightblue", main = tissue)


tissue <- "Liver"
dds_umis_difference <- prepare_difference_dds(dds_umis, dds_md, tissue, sample)

thresholds <- c(0.1,1,2,3,4)
df <- calc_df_for_thresholds(dds_umis_difference, thresholds)
boxplot(df$dif ~ df$threshold, names = thresholds,  outline = FALSE, col = "forestgreen", main = tissue)

thresholds <- c(0.1,1,2,3,4,5,6,7,8)
df <- calc_df_for_thresholds(dds_umis_difference, thresholds)
boxplot(df$dif ~ df$threshold, names = thresholds,  outline = FALSE, col = "forestgreen", main = tissue)


```
