---
title: "OrthologAnalysis"
author: "Luisa Santus"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rtracklayer)
library(tidyverse)
library(dplyr)
library(stringr)
library(scales)

get_stats_liftover <- function(folder, filename, lim = 100 ){
  intersection_table <- read.table(paste(file.path(folder, "intersection.tab")))
  
  bed_macaque <- read.table(paste(file.path(folder, filename), "sorted.bed6", sep = "."))
  bed_human <- read.table(paste(file.path(folder, filename), "human.sorted.bed6", sep = "."))
  bed_human_macaque <- read.table(paste(file.path(folder, filename), "human.macaque.sorted.bed6", sep = "."))
  names(bed_macaque) <- c("chr", "start", "end", "complete_id", "score", "strand")
  names(bed_human) <- c("chr", "start", "end", "complete_id", "score", "strand")
  names(bed_human_macaque) <- c("chr", "start", "end", "complete_id", "score", "strand")
  
  
  names(intersection_table) <- c("chrA", "startA", "endA", "complete_idA", "scoreA", "strandA", "chrB", "startB", "endB", "complete_idB", "scoreB", "strandB", "overlap")
  intersection_table$complete_idA <- as.character(intersection_table$complete_idA)
  intersection_table$complete_idB <- as.character(intersection_table$complete_idB)
  #intersection_table$geneA <- unlist(lapply(intersection_table$complete_idA, function(x) unlist(str_split(x, "_"))[[1]]))
  #intersection_table$geneB <- unlist(lapply(intersection_table$complete_idB, function(x) unlist(str_split(x, "_"))[[1]]))
  
  # Check how many have the same gene overlap or exon overlap
  exon_overlap <- intersection_table %>% dplyr::filter(complete_idA == complete_idB)
  number_exons_with_exact_overlap <- length(unique(exon_overlap$complete_idB))
   
  # total number of exons tested 
  total_exons_beginning <- length(unique(bed_macaque$complete_id))
  total_exons_after_first_liftover <- length(unique(bed_human$complete_id))
  total_exons_after_second_liftover <- length(unique(bed_human_macaque$complete_id))
  
 
   # ORTHOLOGS BIOTYPES 
  intersection_table_biotype <- read.table(paste(file.path(folder, "intersection_human_macaquehuman.tab")))
  names(intersection_table_biotype) <- c("chrA", "startA", "endA", "complete_idA", "scoreA", "strandA", "biotype", "chrB", "startB", "endB", "complete_idB", "scoreB", "strandB", "overlap")
  
  # Get the biotypes for the overlapped exons( the ones matching after both liftovers)
  new_dataset <- intersection_table_biotype %>% right_join(exon_overlap, by=c("complete_idB"))
  correspondence <- as.data.frame(c(new_dataset$complete_idB))
  correspondence$biotype <- as.character(new_dataset$biotype)
  names(correspondence) <- c("id", "biotype")
  correspondence$id <- as.character(correspondence$id)
  
  # remove duplicate rows (distinct) and get biotype's combination occurrence
  correspondence_filtered <- distinct(correspondence) %>% group_by(id) %>% dplyr::summarise(biotype = paste(biotype, collapse=", "))
  
  # Reformat data for plotting
  df <- as.data.frame(as.matrix(table(correspondence_filtered$biotype)))
  df$type <- rownames(df)
  colnames(df) <- c("count", "biotype")
 
  biotype_na <- df[df$biotype == "NA",]$count
  biotype_not_na <- sum(df[df$biotype != "NA",]$count)
  
  # plot with no restrictions
  max = NA
  lim = lim
  p2 <- ggplot(data=df[df$count > lim,][df[df$count > lim,]$biotype != "NA",], aes(x=biotype, y=count, fill=biotype)) +geom_bar(stat="identity", width=0.5) + coord_flip()+  scale_fill_brewer(palette="Paired")+
    theme_minimal() + ylim(0,max) + theme(legend.position = "none") 
  

  labels <- c("1_Total", "2_After1stLiftover", "3_After2ndLiftover", "4_biotype NA", "5_biotypeFound")
  df1 <- as.data.frame(labels)
  if(length(biotype_na) == 0){ biotype_na <- 0}
  df1$count <- c(total_exons_beginning,total_exons_after_first_liftover,total_exons_after_second_liftover,biotype_na, biotype_not_na)
  p1 <- ggplot(data=df1, aes(x = labels,  y=count, fill=labels)) +
    geom_bar(stat="identity")+
    scale_fill_brewer(palette="Paired")+
    theme_minimal()+scale_y_continuous(limits=c(number_exons_with_exact_overlap -1000, total_exons_beginning),oob = rescale_none, labels = function(x) format(x, comma = TRUE))
  

  return(list(p1,p2))
}
```

## Compute number of orthologs

    TODO 

# if number is ok --> check intersect with human annotation to get the biotype, also check for strandness!!!
```{r cars}

folder = "/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/04_orthologs"
folder_lncrna= file.path(folder, "00_lncrna/")
folder_lncrna_05 = file.path(folder, "00_lncrna_05/")
folder_lncrna_025 = file.path(folder, "00_lncrna_025/")
folder_mrna = file.path(folder, "01_mrna/")
filename = "rheMac10_EBOV_and_novel_genenames"

ref <- import(file.path("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/old/03_novel_lncrnas/02_final_catalogue/rheMac10_EBOV-Kikivit_and_novelcatalogue_with_names.gtf"))

folder <- folder_lncrna_05
lncrnas_plot <- get_stats_liftover(folder_lncrna, filename, lim = 1)
#mrns_plot <- get_stats_liftover(folder_mrna, filename)
#folder <- folder_lncrn
de_lnc_all <- readRDS( file.path(robjectsdir, "de_lnc_all.rds"))
de <- gsub("-unkown", "",unlist(de_lnc_all))
length(unique(de))



# Analsysis Orthologs 
folder_input <- folder_lncrna_05
intersection_table <- read.table(paste(file.path(folder_input, "intersection.tab")))
  
bed_macaque <- read.table(paste(file.path(folder_input, filename), "sorted.bed6", sep = "."))
bed_human <- read.table(paste(file.path(folder_input, filename), "human.sorted.bed6", sep = "."))
bed_human_macaque <- read.table(paste(file.path(folder_input, filename), "human.macaque.sorted.bed6", sep = "."))
names(bed_macaque) <- c("chr", "start", "end", "complete_id", "score", "strand")
names(bed_human) <- c("chr", "start", "end", "complete_id", "score", "strand")
names(bed_human_macaque) <- c("chr", "start", "end", "complete_id", "score", "strand")
  
names(intersection_table) <- c("chrA", "startA", "endA", "complete_idA", "scoreA", "strandA", "chrB", "startB", "endB", "complete_idB", "scoreB", "strandB", "overlap")
intersection_table$complete_idA <- as.character(intersection_table$complete_idA)
intersection_table$complete_idB <- as.character(intersection_table$complete_idB)
  
# Check how many have the same gene overlap or exon overlap
exon_overlap <- intersection_table %>% dplyr::filter(complete_idA == complete_idB)
number_exons_with_exact_overlap <- length(unique(exon_overlap$complete_idB))
   
# total number of exons tested 
total_exons_beginning <- length(unique(bed_macaque$complete_id))
total_exons_after_first_liftover <- length(unique(bed_human$complete_id))
total_exons_after_second_liftover <- length(unique(bed_human_macaque$complete_id))
  
 # ORTHOLOGS BIOTYPES 
intersection_table_biotype <- read.table(paste(file.path(folder_input, "intersection_human_macaquehuman.tab")))
names(intersection_table_biotype) <- c("chrA", "startA", "endA", "complete_idA", "scoreA", "strandA", "biotype", "chrB", "startB", "endB", "complete_idB", "scoreB", "strandB", "overlap")
  
# Get the biotypes for the overlapped exons( the ones matching after both liftovers)
new_dataset <- intersection_table_biotype %>% right_join(exon_overlap, by=c("complete_idB"))


full_correspondence <- new_dataset 
correspondence <- new_dataset 


# Remove lines where there is no match 
full_correspondence <- full_correspondence[!is.na(full_correspondence$complete_idA.x), ]
full_correspondence_reduced <- data.frame(human_id_full = as.character(full_correspondence$complete_idA.x), 
                                             macaque_id_full = full_correspondence$complete_idB, 
                                             biotype =full_correspondence$biotype, stringsAsFactors = FALSE)
full_correspondence_reduced$human_gene_id <-  unlist(lapply(full_correspondence_reduced$human_id_full, function(x) strsplit(x,"_")[[1]][1]))
full_correspondence_reduced$macaque_gene_id <-  unlist(lapply(full_correspondence_reduced$macaque_id_full, function(x) strsplit(x,"_")[[1]][1]))

distinct(full_correspondence_reduced) %>% group_by(macaque_id_full, human_id_full) %>% dplyr::summarise(biotype = paste(biotype, collapse=", "))

de_full_corr <- full_correspondence_reduced[full_correspondence_reduced$macaque_gene_id %in% de, ]
de_full_corr_unique <- de_full_corr[!duplicated(de_full_corr$macaque_gene_id),]
de_full_corr_unique$human_gene_id

# test ----

new_dataset <- intersection_table_biotype %>% right_join(exon_overlap, by=c("complete_idB"))
correspondence <- as.data.frame(c(new_dataset$complete_idB))
correspondence$biotype <- as.character(new_dataset$biotype)
names(correspondence) <- c("id", "biotype")
correspondence$id <- as.character(correspondence$id)
correspondence$macaque_id <- unlist(lapply(as.character(correspondence$id), function(x) strsplit(x,"_")[[1]][1]))
correspondence <- correspondence[!is.na(correspondence$biotype),]
# remove duplicate rows (distinct) and get biotype's combination occurrence
correspondence_filtered <- distinct(correspondence) %>% group_by(macaque_id) %>% dplyr::summarise(biotype = paste(biotype, collapse=", "))


correspondence_filtered$biotype_summarized <- unlist(lapply(correspondence_filtered$biotype, function(x) paste(unique(trimws(unlist(str_split(x, ",")))), collapse = ",")))

# Orthologs for how many of my lnc do i find? 
length(unique(correspondence_filtered$macaque_id))
sum(table(correspondence_filtered$biotype_summarized))
ggplot(correspondence_filtered, aes(y = biotype_summarized, fill = biotype_summarized))+geom_bar()+theme_classic()+theme(legend.position = "none")+labs(y = "Biotype")

# I find only 900
correspondence_filtered$type <- unlist(lapply(correspondence_filtered$macaque_id, function(x) substr(x,1,4)))
length(unique(correspondence_filtered$macaque_id))
ggplot(correspondence_filtered, aes(y = biotype_summarized, fill = type))+geom_bar()+theme_classic()+scale_fill_brewer(palette = "Paired")+theme(legend.position = "none")

count_biotype <- as.data.frame(table(correspondence_filtered$biotype_summarized))
count_biotype <- count_biotype[count_biotype$Freq > 10, ] 
biotypes_keep <- as.vector(count_biotype$Var1)

ggplot(correspondence_filtered[correspondence_filtered$biotype_summarized %in% biotypes_keep, ], aes(y = biotype_summarized, fill = type))+geom_bar()+theme_classic()+scale_fill_brewer(palette = "Paired")+theme(legend.position = "none")+labs(y = "Biotype")


# How many of the De genes 
de_lnc_orthologs <- correspondence_filtered[correspondence_filtered$macaque_id %in% de, ]
ggplot(de_lnc_orthologs, aes(y = biotype_summarized, fill = type ))+geom_bar()+theme_classic()+scale_fill_brewer(palette = "Paired")+labs(y = "Biotype")



full_correspondence[full_correspondence$complete_idA.x %in% de, ]

# Check overlap with pan cancer lncRNA analysis
sign_pathway <- read.table("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/04_orthologs/Lnc_Pathways_Sig.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
sign_cell <- read.table("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/04_orthologs/Lnc_Immunecell_Sig.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
sign_cancer <- read.table("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/04_orthologs/LncRNA_Cancer_Sig.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)



de_ortholgs_immlnc <- sign_pathway[sign_pathway$lncRNA_id %in% unlist(lapply(de_full_corr$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])),]
de_ortholgs_cancer <- sign_cancer[sign_cancer$lncRNA_id %in% unlist(lapply(de_full_corr$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])),]
de_ortholgs_cell <- sign_cell[sign_cell$lncRNA_id %in% unlist(lapply(de_full_corr$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])),]


de_ortholgs_immlnc_reduced <- data.frame(id = de_ortholgs_immlnc$lncRNA_id, 
                                         pathway = de_ortholgs_immlnc$immune_pathway, 
                                         pval = de_ortholgs_immlnc$p_adjust, 
                                         cancer  = de_ortholgs_immlnc$cancer_type
                                         )


imm_lnc_matches_distr <- de_lnc_orthologs[unlist(lapply(de_lnc_orthologs$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])) %in% de_ortholgs_immlnc_reduced$id,]

theme_paper <- theme_minimal()+ theme(panel.background = element_rect(fill = "white", colour = "grey50"), panel.grid.major = element_blank(), panel.grid.minor = element_blank())


ggplot(distinct(de_ortholgs_immlnc_reduced), aes(y = pathway, fill = id, color = cancer ))+geom_bar()+theme_classic()+labs(fill = "Gene ID")+scale_fill_brewer(palette = "Accent")+scale_color_manual(values = rep("grey", length(de_ortholgs_immlnc_reduced$cancer)))+guides( color = FALSE)+theme_paper


full_correspondence_orthologs <- full_correspondence_reduced[unlist(lapply(full_correspondence_reduced$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])) %in% de_ortholgs_immlnc_reduced$id, ]

my_de_ortholog <- unique(full_correspondence_orthologs$macaque_gene_id[as.character(full_correspondence_orthologs$macaque_gene_id) %in% gsub("-unkown", "", unlist(de_lists_lnc_my))])

length(my_de_ortholog)

T_de_ortholog <- unique(full_correspondence_orthologs$macaque_gene_id[as.character(full_correspondence_orthologs$macaque_gene_id) %in% gsub("-unkown", "", unlist(de_lists_lnc_T))])

length(T_de_ortholog)

B_de_ortholog <- unique(full_correspondence_orthologs$macaque_gene_id[as.character(full_correspondence_orthologs$macaque_gene_id) %in% gsub("-unkown", "", unlist(de_lists_lnc_B))])
length(B_de_ortholog)

full_correspondence_orthologs$human_id_simple <- unlist(lapply(full_correspondence_orthologs$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1]))


de_ortholgs_immlnc_reduced$human_id_simple <- as.character(de_ortholgs_immlnc_reduced$id)
full_correspondence_orthologs$human_id_simple

length(unique(de_ortholgs_immlnc_reduced$id))

full_for_join <- data.frame( human_id_simple = full_correspondence_orthologs$human_id_simple, 
                             macaque_id = full_correspondence_orthologs$macaque_gene_id, stringsAsFactors = FALSE ) 

de_full_corr <- de_ortholgs_immlnc_reduced %>% join(full_for_join, by=c("human_id_simple"))
length(unique(de_full_corr$macaque_gene_id))

unique(de_ortholgs_immlnc_reduced[de_ortholgs_immlnc_reduced$pathway == "Cytokines",]$id)
unique(de_full_corr[de_full_corr$pathway == "Cytokines",]$id)

nrow(de_full_corr)
de_full_corr$orth_id <- paste(de_full_corr$macaque_id, "-> ", de_full_corr$human_id_simple)

ggplot(distinct(de_full_corr), aes(y = pathway, fill = macaque_id, color = cancer ))+geom_bar()+theme_classic()+labs(fill = "Macaque Gene ID", y = "Pathway")+scale_fill_brewer(palette = "Set3")+scale_color_manual(values = rep("darkgrey", length(de_ortholgs_immlnc_reduced$cancer)))+guides( color = FALSE)+theme_paper


intersect(B_de_ortholog, T_de_ortholog)
intersect(my_de_ortholog, T_de_ortholog)
intersect(B_de_ortholog, my_de_ortholog)


myeloids_de[myeloids_de$primerid %in% my_de_ortholog, ]

# test ---- end

ggplot(correspondence_filtered[correspondence_filtered$biotype_summarized %in% biotypes_keep, ], aes(y = biotype_summarized, fill = type))+geom_bar()+theme_classic()+scale_fill_brewer(palette = "Paired")+theme(legend.position = "none")+labs(y = "Biotype")+theme(axis.text = element_text(size = 17))

ggplot(correspondence_filtered, aes(y = biotype_summarized, fill = type))+geom_bar()+theme_classic()+scale_fill_brewer(palette = "Paired")+theme(legend.position = "none")+labs(y = "Biotype")
ggplot(de_lnc_orthologs, aes(y = biotype_summarized, fill = type ))+geom_bar()+theme_classic()+scale_fill_brewer(palette = "Paired")+labs(y = "Biotype")+theme(axis.text = element_text(size = 17))


# How many orthlogs i find 
length(unique(correspondence_filtered$macaque_id))

# How many are novel and how many annotated
table_number_orthologs <-table(substr(unique(correspondence_filtered$macaque_id),1,3))
table_number_orthologs*100/sum(table_number_orthologs)


table(correspondence_filtered$biotype_summarized)*100/sum(table(correspondence_filtered$biotype_summarized))



```

```{r rest }

# Orthologs Stats 
# Out of all the lncRNAs for which we tried to get the ortholgs this is what we find. 

# In general stats about lnc we have in reference
ref[substr(ref$gene_id, 1,3) %in% c("pol", "rib"), ]$gene_biotype <- "lncRNA"
table(ref[substr(ref$gene_id, 1,3) %in% c("pol", "rib"), ]$gene_biotype)
table(ref$gene_biotype)
lnc<- ref[!is.na(ref$gene_biotype) & ref$gene_biotype == "lncRNA", ]
length(unique(gtf[gtf$gene_biotype == "lncRNA", ]$gene_id)) # 7k
lnc_distr <- as.data.frame(table(unlist(lapply(unique(lnc$gene_id), function(x) substr(x,1,4)))))
names(lnc_distr) <- c("type", "count")
ggplot(lnc_distr, aes(x = "", y = count, fill = type))+geom_bar(stat =  "identity")+coord_polar("y", start = 0)+
  theme_minimal()+
  scale_fill_brewer(palette = "Paired")+
  geom_text(label = lnc_distr$count, size = 5, aes(y = c(6000,900,2100)))+
  theme(axis.text.x = element_blank())



lnc_orthologs <- full_correspondence_reduced[!is.na(full_correspondence_reduced$biotype), ]
lnc_orthologs_unique <- lnc_orthologs[!duplicated(lnc_orthologs$macaque_gene_id),]
# General plot
ggplot(lnc_orthologs_unique, aes(y = biotype, fill = biotype))+geom_bar()+theme_classic()+theme(legend.position = "none")

# I find only 900
lnc_orthologs_unique$type <- unlist(lapply(lnc_orthologs_unique$macaque_gene_id, function(x) substr(x,1,4)))
length(unique(lnc_orthologs_unique$macaque_gene_id))
ggplot(lnc_orthologs_unique, aes(y = biotype, fill = type))+geom_bar()+theme_classic()+scale_fill_brewer(palette = "Paired")

# How many of the De genes 
de_lnc_orthologs <- lnc_orthologs_unique[lnc_orthologs_unique$macaque_gene_id %in% de, ]
ggplot(de_lnc_orthologs, aes(y = biotype, fill = type ))+geom_bar()+theme_minimal()+scale_fill_brewer(palette = "Paired")


# Check overlap with pan cancer lncRNA analysis
sign_pathway <- read.table("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/04_orthologs/Lnc_Pathways_Sig.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
sign_cell <- read.table("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/04_orthologs/Lnc_Immunecell_Sig.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
sign_cancer <- read.table("/home/luisas/Desktop/cluster/data/01_bulk_RNA-Seq_lncRNAs_annotation/03_novel_lncRNAs_list/04_orthologs/LncRNA_Cancer_Sig.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

de_ortholgs_immlnc <- sign_pathway[sign_pathway$lncRNA_id %in% unlist(lapply(de_lnc_orthologs$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])),]
de_ortholgs_cancer <- sign_cancer[sign_cancer$lncRNA_id %in% unlist(lapply(de_lnc_orthologs$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])),]
de_ortholgs_cell <- sign_cell[sign_cell$lncRNA_id %in% unlist(lapply(de_lnc_orthologs$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])),]


de_ortholgs_immlnc_reduced <- data.frame(id = de_ortholgs_immlnc$lncRNA_id, 
                                         pathway = de_ortholgs_immlnc$immune_pathway
                                         )


imm_lnc_matches_distr <- de_lnc_orthologs[unlist(lapply(de_lnc_orthologs$human_gene_id, function(x) strsplit(x,"[.]")[[1]][1])) %in% de_ortholgs_immlnc_reduced$id,]



de_ortholgs_immlnc_reduced

ggplot(distinct(de_ortholgs_immlnc_reduced), aes(y = pathway, fill = id))+geom_bar()+theme_minimal()


distinct(de_ortholgs_immlnc_reduced) %>% group_by(id) %>% dplyr::summarise(pathway = paste(pathway, collapse=", "))

```
