#!/bin/bash

# Array with all the tissues
declare -a arr=("Spleen" "Kidney" "Liver" "Brain" "Lymph node" "Lung" "Skin" "Adrenal Gland" "Whole blood")
#declare -a arr=("Spleen")

# Loop through the tissues
for i in "${arr[@]}"
do
   echo "$i"
   #Rscript ./00.prepare.counts.R "$i"
   Rscript ./01.voom_limma.R "$i"
   Rscript ./02.plots_de.R "$i"
   Rscript ./03.plots_de_summary.R "$i"
done
